project:
  type: website
  execute-dir: project
  output-dir: _site
  render:
      - index.qmd
      - topic*.qmd

website:
  title: "Comparative methods on networks"
  site-url: https://cecileane.github.io/networkPCM-workshop
  repo-url: https://github.com/cecileane/networkPCM-workshop
  repo-actions: [issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: http://crsl4.github.io/PhyloNetworks.jl/latest/
        text: PhyloNetworks
    right:
      - icon: github
        href: https://github.com/cecileane/networkPCM-workshop
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - topic-overview.qmd
      - topic1-netcalibration.qmd
      - topic2-phyloANOVA.qmd
      - topic3-asr.qmd
      - topic4-impactgeneflow.qmd
      - topic5-discrete.qmd
      - topic6-visualization.qmd
      - topic7-averagedistances.qmd
  page-navigation: true

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

jupyter: julia-1.8
